import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import data from "../components/data";
import { Navbar } from "../components/Navbar";
import { Hero } from "../components/Hero";
import { Card } from "../components/Card";

export default function Home() {
	const products = data.map(product => {
		return (
			<Card
				key={product.id}
				{...product}
			/>
		);
	});
	return (
		<div className={styles.container}>
			<Head>
				<title>AirBnb Experiences Clone</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/airbnb-icon.png" />
			</Head>
			<Navbar />
			<Hero />
			<section className={styles.cards}>
				{products}
			</section>
		</div >
	);
}
